package_assets:          on
embed_assets:            off
compress_assets:         on
gzip_assets:             on
javascript_compressor:   yui
template_function:       _.template

javascripts: 
  base: 
    - vendor/e9_base/app/javascripts/vendor/jquery-1.4.2.js
    - vendor/e9_base/app/javascripts/vendor/jquery-ui-1.8.6.custom.js
    - vendor/e9_base/app/javascripts/vendor/base/*.js
    - vendor/e9_base/app/javascripts/e9/base.js
    - vendor/e9_base/app/javascripts/e9/base/*.js
    - vendor/e9_base/app/javascripts/application.js
    - public/javascripts/jquery.cycle.all.js
    - public/javascripts/flash.js
    - public/javascripts/application.js

  images:
    - vendor/e9_base/app/javascripts/vendor/images/*.js
    - vendor/e9_base/app/javascripts/e9/images/crop.js
    - vendor/e9_base/app/javascripts/e9/images/upload.js
    - vendor/e9_base/app/javascripts/e9/images/upload_and_crop.js

  slideshows:
    - vendor/e9_base/app/javascripts/vendor/slideshows/*.js
    - vendor/e9_base/app/javascripts/e9/slideshows.js

  slides:
    - vendor/e9_base/app/javascripts/vendor/slides/*.js
    - vendor/e9_base/app/javascripts/e9/slides.js
    - app/views/layouts/application/default/slides/*.jst

  admin:
    - vendor/e9_base/app/javascripts/vendor/admin/*.js
    - vendor/e9_base/app/javascripts/e9/admin.js
    - vendor/e9_base/app/javascripts/e9/admin/*.js
    - vendor/e9_base/engines/e9_crm/app/views/e9_crm/**/*.jst
